base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: true
load_in_4bit: false
strict: false


datasets:
  - path: /HDD/sofi/log_creation/imdb/imdb_chat.jsonl
    type: chat_template
    chat_template: llama3
    field_messages: messages
    message_field_role: role 
    message_field_content: content
    roles_to_train: ["assistant"]
    train_on_eos: last
dataset_prepared_path: /HDD/sofi/log_creation/imdb/
val_set_size: 0.05
output_dir: /HDD/sofi/log_creation/imdb/model_chat/

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 16 
lora_alpha: 32
lora_dropout: 0.1 
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
  - embed_tokens
  - lm_head

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed: 
weight_decay: 0.01
fsdp:
fsdp_config:
special_tokens:
   pad_token: <|end_of_text|>